window.siteContent = {
  brand: "Anya Biarozka",
  heroKicker: "I design products, brands and systems for businesses in the age of AI.",
  heroStatement: "Helping startups and established organizations transform complexity into scalable products, meaningful experiences, and lasting impact.",
  workStatement: "Selected Projects",
  clientsLabel: "Clients I've worked with include...",
  footerDescriptor: "Creative Director & Senior Product Designer\nfor Product, Brand & AI Automation\n| Berlin-Based",
  mailLabel: "Mail",
  email: "anya.biarozka@gmail.com",
  locationOne: "Amsterdam / Berlin",
  locationTwo: "New York",
  images: {
    heroImage: "./assets/bg.png",
    recognitionImage: "./assets/recognition-photo-w.png"
  },
  projects: [
    {
      slug: "pulse-mindfulness",
      title: "Pulse Mindfulness",
      meta: "UX/UI, Branding",
      image: "./assets/pulse-homepage.png",
      detailCoverImage: "./assets/pulse-gold-3.png",
      year: "2025–2026",
      headline: "Designing a wearable ecosystem for mindfulness, focus, and habit formation",
      overview: "<a href=\"https://www.pulsemindfulness.com/\" target=\"_blank\" rel=\"noreferrer\" class=\"detail-inline-link\">Pulse Mindfulness</a> is a wearable smart ring that uses subtle haptic cues to help people build mindfulness habits, stay focused, and be more present throughout the day.\n\nI partnered with the founder and lead developer to take the product from concept to launch. I led the UX and UI design of the companion app and wearable ecosystem, shaped the brand identity, and developed the strategic investor pitch deck. I defined the product experience across onboarding, device control, personalization, and future product strategy. Together, the ring and app create a connected experience that supports lasting mindful habits.",
      services: ["UX Leadership", "Product Strategy", "Business Thinking", "Product & Wearable Experience Design", "Visual Design", "Brand Direction", "Marketing Design", "Website Design", "Investor Pitch Narrative & Presentation Design"],
      role: ["Senior Designer"],
      industry: ["Wellness", "Wearables", "Consumer Technology"],
      challengeTitle: "Challenge",
      challengeCopy: "Designing a mindfulness product meant balancing a contradiction: using technology to help people disconnect.\n\nThe challenge was to create a calm, unobtrusive experience where the ring remained simple and ambient, while the app provided personalization, setup, and device control without becoming a distraction. At the same time, the product needed a scalable foundation to support user retention, premium features, and future growth.",
      challengeImage: "./assets/img-4.png",
      challenge2Title: "Experience Design",
      challenge2Copy: "I designed the companion app as the control layer of the Pulse ecosystem, enabling users to set up and personalize their experience, manage their device, create intentions, and build mindfulness routines.\n\nThe app complements the ring's subtle haptic cues, providing deeper functionality when needed while keeping the overall experience simple and unobtrusive.",
      challenge2Image: "./assets/pulse-img-4.png",
      challenge2Video: "./assets/pulse-video-4.mp4",
      fullscreenImage2: "./assets/pulse-img-6.png",
      challenge3Title: "Control & Pairing",
      challenge3Copy: "A major focus was designing the wearable control experience.\n\nI created onboarding, Bluetooth pairing, reconnection, device management, and recovery flows, ensuring the technology felt reliable and effortless. These interactions are often overlooked, but they directly influence trust in a hardware product.",
      challenge3Image: "./assets/pulse-img-7.png",
      challenge5Title: "Personalization & Business Value",
      challenge5Copy: "At the core of the experience is intention-setting, allowing users to connect the ring's haptic cues to personal goals rather than generic reminders.\n\nI designed a flexible personalization model with guided intentions for ease of use and deeper customization as part of the premium experience. This reduced onboarding friction, encouraged long-term engagement, and supported a clear subscription value proposition.",
      challenge5Video: "./assets/pulse-video-8.mp4",
      fullscreenImage3: "./assets/pulse-img-9.png",
      challenge4Title: "Designing for Growth",
      challenge4Copy: "I designed the app as a scalable foundation for the Pulse ecosystem, balancing a simple day-to-day experience with the flexibility to support new features, premium offerings, and future growth. This included envisioning social and connected experiences, such as shared mindfulness moments between partners, families, or groups through synchronized haptic cues.",
      fullscreenImage4: "./assets/pulse-img-13.png",
      fullscreenImage5: "./assets/pulse-img-14.png",
      challenge6Title: "Audience-Specific Landing Pages",
      challenge6Copy: "I designed two landing page experiences tailored to different audiences: wellness-focused users seeking mindfulness and presence, and busy professionals looking to improve focus and attention. Both experiences used audience-specific messaging and visuals before leading into a shared order flow, creating a more relevant and effective path to purchase.",
      challenge6Image: "./assets/pulse-img-12.png",
      challenge7Title: "Outcome",
      challenge7Copy: "Pulse launched recently, so long-term metrics are still emerging.\n\nThe result is a wearable ecosystem that balances simplicity with personalization, supports sustainable habit formation, and creates a scalable foundation for future growth.",
      challenge7Image: "./assets/pulse-img-11.png",
      challenge4Image: "./assets/pulse-img-10.png",
      fullscreenImage: "./assets/pulse-img-5.png",
      fullscreenImageSquare: true,
      gallery: ["./assets/pulse-right.png", "./assets/pulse-third.png"]
    },
    {
      slug: "audi",
      title: "Audi",
      meta: "UI Introduction for the Brand Appearance - Audi.com",
      relatedProjects: ["foormly", "5sinne"],
      introVideo: "./assets/audi-video-1.mp4",
      introVideoLink: { label: "Brand Appearance - Audi.com", href: "https://styleguide.audi.com/document/2865" },
      image: "./assets/audi-img-1.avif",
      detailCoverImage: "./assets/audi-img-1.avif",
      year: "2018",
      headline: "Bringing Audi's Brand Appearance design system to life through a UI Introduction",
      overview: "Created as part of Audi's Brand Appearance initiative, this UI Introduction demonstrates the core principles of the design system in action.\n\nBuilt around a car booking concept, the video walkthrough shows how components and modules combine across real interface scenarios — giving designers and teams a practical visual reference for applying the system consistently and at scale.\n\nWith <a href=\"https://sp.design.de\" target=\"_blank\" rel=\"noreferrer\" class=\"detail-inline-link\">sp.design.de</a>",
      services: ["UI Design", "Brand System"],
      role: ["UI/UX Designer"],
      industry: ["Automotive"],
      gallery: []
    },
    {
      slug: "foormly",
      title: "FOORMLY",
      meta: "Strategy, brand identity, design",
      image: "./assets/foormly-homepage.png",
      detailCoverImage: "./assets/foormly-homepage.png",
      layout: "wide",
      year: "2025",
      headline: "Designing an AI-powered wellness app for personalized meditation and emotional wellbeing",
      overview: "Foormly is a wellness app that combines AI technology with psychological expertise to enable users to create personalized, dynamically generated intimate meditations and affirmations based on individual needs, using voice and sound.\n\nI worked across research, product strategy, branding, visual design, and product design, helping shape the experience from early concept through product definition.",
      services: ["Product Strategy", "User Research", "User Journey Mapping", "Workshop Facilitation", "Product Design", "UX Design", "Visual Design", "Brand Direction"],
      role: ["Senior Designer"],
      industry: ["Health & Wellness", "AI"],
      challengeTitle: "Challenge",
      challengeCopy: "Most wellness apps rely on static content that struggles to address users' unique emotional states and personal goals. The challenge was to create a more adaptive experience that felt personal, meaningful, and trustworthy while leveraging the capabilities of AI.",
      challengeImage: "./assets/foormly-img-f-4.png",
      beforeFSTitle: "Designing the Experience",
      beforeFSCopy: "I mapped the end-to-end user journey, defining how users discover, personalize, and engage with AI-generated content. The experience was designed around personal intention and long-term habit formation rather than content consumption alone.\n\nTo align user needs, business goals, and technical feasibility, I also designed and facilitated feature prioritization workshops that helped shape the product roadmap and future vision.",
      beforeFSImage: "./assets/foormly-img-f-7.png",
      fullscreenImage: "./assets/foormly-img-f-6.png",
      fullscreenImage2: "./assets/foormly-img-f-8-updated.png",
      fullscreenImage4: "./assets/foormly-img-f-9.png",
      fullscreenLabel4: "Pitch Deck",
      fullscreenImage4Wide: true,
      fullscreenLabel: "User Journey",
      challenge2Title: "Research & Strategy",
      challenge2Copy: "Designed and led user research, analyzed responses, and identified key pain points and opportunities. Combined with market analysis, the insights informed product strategy, feature prioritization, and experience direction.",
      challenge2Image: "./assets/foormly-img-f-5.png",
      relatedProjects: ["5sinne", "onchain-capital-allocation-handbook"],
      gallery: ["./assets/foormly-img-f-2.png", "./assets/foormly-img-f-3.png"]
    },
    {
      slug: "5sinne",
      relatedProjects: ["onchain-capital-allocation-handbook", "pulse-mindfulness"],
      title: "5Sinne",
      meta: "UX/UI, Interactive",
      image: "./assets/ixian-homepage.png",
      detailCoverImage: "./assets/ixian-homepage.png",
      year: "2026",
      headline: "A Scalable Brand Architecture for Diverse Ventures",
      overview: "5Sinne GmbH is a German holding company uniting ventures across hospitality, immersive experiences, food expertise, festivals, and cultural concepts.",
      services: ["Brand Identity"],
      role: ["Creative Director"],
      industry: ["Hospitality & Experience Group"],
      challengeCopy: "The challenge was to create a brand identity that reflects the diversity of the group while providing a clear framework for communicating its different business directions to partners and stakeholders.",
      challengeImage: "./assets/5sinne-img-3.png",
      fullscreenImage: "./assets/5sinne-img-4.png",
      fullscreenImage2: "./assets/5sinne-img-5.png",
      fullscreenImagesWide: true,
      challenge3Reverse: false,
      challenge3Image: "./assets/5sinne-img-6.png",
      fullscreenImage3: "./assets/5sinne-img-7.png",
      fullscreenImage4: "./assets/5sinne-img-8.png",
      challenge3Copy: "Inspired by the meaning of \"5Sinne\" (\"five senses\"), the logo translates this concept into a dynamic symbol. Each branch represents both a sense and a business vertical, expressed through a distinct color system.\n\nThis approach creates a flexible and scalable identity architecture: individual colors can be used across marketing communications to clearly differentiate each business direction while maintaining a strong connection to the master brand.",
      gallery: ["./assets/5sinne-img-2.png", "./assets/5sinne-img-2b.png"]
    },
    {
      slug: "onchain-capital-allocation-handbook",
      title: "Onchain Capital Allocation Handbook",
      meta: "Editorial, Interactive",
      image: "./assets/ocah-cover.png",
      detailCoverImage: "./assets/ocah-cover.png",
      year: "2024–2025",
      role: ["Creative Director"],
      industry: ["Web3"],
      headline: "Designing a systems-based approach to communicating Web3 complexity",
      overview: "The Onchain Capital Allocation Handbook by Kevin Owocki explores 33 emerging mechanisms for allocating capital within decentralized ecosystems.",
      services: ["Editorial Design", "Information Design", "Generative Design"],
      challengeCopy: "My challenge was to transform a dense collection of interconnected concepts into an experience that felt approachable, engaging, and easy to navigate. Rather than presenting the mechanisms as isolated topics, I designed the publication as a living system inspired by L-systems — algorithms originally developed by Aristid Lindenmayer to model plant growth.",
      challengeImage: "./assets/ocah-img-4.png",
      fullscreenImage: "./assets/ocah-img-5.png",
      fullscreenImage2: "./assets/ocah-img-6.png",
      fullscreenImage3: "./assets/ocah-img-7.png",
      gallery2: ["./assets/ocah-img-9.png", "./assets/ocah-img-8.png"],
      fullscreenImage4: "./assets/ocah-img-10.png",
      challenge2Copy: "Each mechanism was visualized as a unique plant within a larger networked garden, allowing readers to move from a macro view of the ecosystem to the details of individual mechanisms. This approach translated complexity into a visual metaphor that made relationships, patterns, and dependencies easier to understand.\n\nBeyond creating a distinctive reading experience, the system was designed for scalability. The visual framework can continuously evolve as new mechanisms emerge and community contributions expand the body of knowledge, enabling future editions to grow without requiring a fundamental redesign.",
      challenge2Image: "./assets/ocah-img-3.png",
      fullscreenImagesWide: true,
      topFullscreenImage: "./assets/ocah-img-1.png",
      gallery: []
    }
  ],
  clients: [
    { label: "Audi", logo: "./assets/audi-logo.svg" },
    { label: "Porsche", logo: "./assets/porsche-logo.png", className: "client-logo--porsche" },
    { label: "Volkswagen", logo: "./assets/volkswagen-logo.png", className: "client-logo--volkswagen" },
    { label: "Logo", logo: "./assets/logo-bw.svg", className: "client-logo--custom" },
    { label: "Gitcoin", logo: "./assets/gitcoin-logo.svg", className: "client-logo--gitcoin" },
    { label: "Maison Michel", logo: "./assets/maison-michel-logo.webp", className: "client-logo--maison" }
  ],
  socials: [
    { label: "LinkedIn", href: "https://www.linkedin.com/in/anya-biarozka-898b9388" },
    { label: "X", href: "https://x.com/CionaAnoic" },
    { label: "Behance", href: "https://www.behance.net/Biarozka" }
  ]
};
